spring:
  application:
    name: Sample Actuator

logging:
  level:
    root: INFO


server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /sample-actuator

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
        - health
        - metrics
        - info
        - env
    metrics:
      enable:
        jvm.memory.used: true
        process.uptime: true
        process.cpu.usage: true
        all: false
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@